### ISSUE TITLE
support for primitive return types?

### ISSUE THREAD

**Issue by albertalquisola** [atulmy/gql-query-builder#12]
it seems the builder expects an object to always be returned in a graphql response since the `fields` arg is required.  But what if the graphql server responds with a primitive? (eg. GraphQLBoolean)

Example:
```
// mutation portion of schema
new GraphQLObjectType({
  name: 'RootMutation',
  fields: { 
    logout: {
      type: GraphQLBoolean,
      resolve: async () => await pretendToLogUserOut(), // returns boolean
    }
  }
});
```
```
// query
import { mutation } from 'gql-query-builder';

const logoutMutation = mutation({ operation: 'logout', fields: [] });
console.log(logoutMutation.query);
```
```
// query output
mutation {
  logout {
    // this causes a 400 since i dont list any fields but that's because the response doesnt return `fields`, it just returns a bool
  }
}

// desired query output
mutation {
  logout
}
```
The result is a 400 since this is a malformed query string so it seems the query builder does not have support for handling primitive return values?

**Comment by atulmy** [comment]
Check: https://github.com/atulmy/gql-query-builder/issues/8#issuecomment-481789433

**Comment by albertalquisola** [comment]
I'm unsure how this addresses the issue? I dont need to specify a custom variable type (i dont think), I need my query output to not always expect an object being returned

**Comment by atulmy** [comment]
Sorry got it, you want the `fields` to be optional

![Screenshot 2019-05-29 at 12 15 04 AM](https://user-images.githubusercontent.com/685786/58503762-de8f5380-81a6-11e9-84ef-da312df40189.png)
