### ISSUE TITLE
Operation name

### ISSUE THREAD

**Issue by atulmy** [atulmy/gql-query-builder#19]
Reference: https://graphql.org/learn/queries/#operation-name

Current:
```
query {
  thoughts {
    id,
    name,
    thought
  }
}
```

Option to pass query name `ThoughtList`
```
query ThoughtList {
  thoughts {
    id,
    name,
    thought
  }
}
```

**Comment by Devorein** [comment]
That could be solved by replacing the resultant query via `generated.query = generated.query.replace('query',`query ${opName}`);`

But I assume that it could be added to the api itself as part of an argument to the query, mutation and subscription functions.
