### ISSUE TITLE
v3.1.2 breaks build

### ISSUE THREAD

**Issue by henrykuzmick** [atulmy/gql-query-builder#21]
Since v3.1.2 importing breaks typescript builds (not sure if the same happens with js)

**Comment by bradcypert** [comment]
Running into the same issue here with TypeScript.

**Comment by milewski** [comment]
Thats because the latest version is missing the source files...

![image](https://user-images.githubusercontent.com/2874967/63097745-cd830100-bfa3-11e9-9332-180d4c352f5e.png)

**Comment by bradcypert** [comment]
@milewski Who needs those? 😝

**Comment by atulmy** [comment]
My bad. Fixed.

**Comment by thealjey-eib** [comment]
@atulmy I believe that this is the case again with 3.5.2

**Comment by atulmy** [comment]
Sorry about that, took a while to wrap my head around GitHub Actions CI/CD setup. Resolved, v3.5.4 should work.
