### ISSUE TITLE
[suggestion] type for variables

### ISSUE THREAD

**Issue by dlq84** [atulmy/gql-query-builder#26]
variables should have a type, it is well defined in the README but uses `any`. 

My suggestion:

```
type Value = string | number | boolean | Record<string, any>;

interface Variables {
  value: Value;
  type?: string;
  required?: true;
}

type VariablesRecord<T extends Record<string, any> = Record<string, any>> = Record<keyof T, Variables>;

```

and `query<T>()` `mutate<T>()` etc

**Comment by atulmy** [comment]
@dlq84 feel free to open a PR for this use case.

**Comment by Devorein** [comment]
This has been included in the latest release (in a limited way) @dlq84
