### ISSUE TITLE
Single query, multiple operations

### ISSUE THREAD

**Issue by bebraw** [atulmy/gql-query-builder#4]
I have a case roughly like this:

```graphql
query SpeakerTweetTemplateQuery($conferenceId: ID!, $contactName: String!) {
  contact(contactName: $contactName, conferenceId: $conferenceId) {
    name
  }
  conference(id: $conferenceId) {
    name
  }
}
```

The point is that I would like to execute multiple operations within a single query. As far as I can see, the current API isn't flexible enough for this purpose.

I can work around this by performing multiple separate requests. Any better ideas? Should I try to PR a generalization like this?

**Comment by atulmy** [comment]
@bebraw yes, current implementation is quite basic. If we have this feature baked in, it'd definitely help.

There is [this issue](https://github.com/atulmy/gql-query-builder/issues/3) open to support params on nested fields which seems like dependency for this use case as well.

If you can send a PR, that would be awesome. Don't forget to add you name under [Authors](https://github.com/atulmy/gql-query-builder#authors) section of readme. Looking forward to it.

**Comment by bebraw** [comment]
@atulmy Ok, I'll give it a go. Given the feature might couples operation with specific field, likely the API shape has to change. Would a major version be ok? I can likely support the old format while giving a deprecation warning.

**Comment by atulmy** [comment]
> Would a major version be ok? I can likely support the old format while giving a deprecation warning.
Sure.

**Comment by bebraw** [comment]
Here's are my first proposals for the API:

**1.**

```javascript
import queryBuilder from 'gql-query-builder'

const query = queryBuilder([
  {
    type: 'query',
    operation: 'thoughts',
    fields: ['id', 'name', 'thought']
  },
  {
    type: 'query',
    operation: 'prayers',
    fields: ['id', 'name', 'prayer']
  }
])

console.log(query)

// Output
query {
  thoughts {
    id,
    name,
    thought
  }
  prayers {
    id,
    name,
    prayer
  }
}
```

**2.**

```javascript
import queryBuilder from 'gql-query-builder'

const query = queryBuilder.query([{
    operation: 'thoughts',
    fields: ['id', 'name', 'thought']
  },
  {
    operation: 'prayers',
    fields: ['id', 'name', 'prayer']
  }
])

console.log(query)

// Output
query {
  thoughts {
    id,
    name,
    thought
  }
  prayers {
    id,
    name,
    prayer
  }
}
```

Does it make sense to generate a query that has both mutations and queries in it? If not, then I would go with 2. as then you get `.query` and `.mutation` and cannot end up with a conflicting state.

Let me know what you prefer and I'll implement the variant.

**Comment by atulmy** [comment]
@bebraw the second one looks more comprehensible.

We may also need to support:
Only object:
```
queryBuilder.query({ ... })
```

Array of objects:
```
queryBuilder.query([ { ... }, { ... } ])
```

And mutation as well:
```
queryBuilder.mutation()
```

**Comment by bebraw** [comment]
@atulmy Ok, sounds good. I'll do something basic around this. Would you mind if I ported the project to TypeScript while at it?

**Comment by atulmy** [comment]
> port the project to TypeScript
Sure. Sounds exciting. Haven't worked with TypeScript yet, this sounds like a good opportunity.

**Comment by bebraw** [comment]
@atulmy You can find my initial PR at #5. It doesn't include the work above, though.

**Comment by atulmy** [comment]
I think we should support following:
```
const { query, mutation } = require('gql-query-builder')

query()

mutation()
```

```
const queryBuilder = require('gql-query-builder')

queryBuilder.query()

queryBuilder.mutation()
```

**Comment by bebraw** [comment]
Ok, cool. I'll prepare a PR along those lines. It might go to tomorrow. Let's see.

**Comment by atulmy** [comment]
Sure, we can schedule an `npm` release once updated API is in good shape.
