### ISSUE TITLE
mutation - variable with null value

### ISSUE THREAD

**Issue by honzahk** [atulmy/gql-query-builder#49]
consider this code server-side
```
type Mutation {
  updateMessage(id: Number!, text: String): Boolean
}
```
and this code client-side
```
const mutation = gql.mutation({
    operation: 'updateMessage',
    variables: {
        id: {value: 1, required: true},
        text: null
  }
})
```
---
now if you print out the mutation, `text` variable has `Object` type
```
console.log(mutation);

//query
mutation ($id: Int!, $text: Object) {
  updateMessage (id: $id, text: $text) 
}

//variables
{
    id: 1,
    text: null
}
```
the reason is obvious, `gql-query-builder` cannot determine the type when just `null` is provided - it might be any type.

---

if you send this mutation to the server-side, in response you get error
```
message: "Unknown type "Object"."
```
server-side does not know type `Object`; moreover the type coming from client-side (infered by `gql-query-builder`) has to correspond with the type defined on server-side (in graphql schema)

---

by now, i use workaround by specifing the variable type explicitly
```
const mutation = gql.mutation({
    operation: 'updateMessage',
    variables: {
        id: {value: 1, required: true},
        text: {value: null, type: "String"}
  }
})
```
**is this workaround alright or is there a better way?** 
i cannot think of any other ways, as it is impossible to know the intended type when just `null` is provided.

thanks in advance!

**Comment by Devorein** [comment]
Yes that is the only way to accurately say what the type of that variable is in a query
