### ISSUE TITLE
TypeError: innerFields.forEach is not a function

### ISSUE THREAD

**Issue by bujanov** [atulmy/gql-query-builder#56]
Hi!

I get an error when I try to collect a query
`TypeError: innerFields.forEach is not a function`

For example, the query is as follows
`[ 
    {
       operation: 'someoperation',
       fields: [
          'id',
          { 
              operation: 'someoperation2',
              fields: [ 'name' ] 
          } 
       ]
   } 
]`

**Comment by ShtiviGrin** [comment]
I'm having the same issue.

**Comment by FrankMbappe** [comment]
Any updates on this?

**Comment by marfalkov** [comment]
https://github.com/atulmy/gql-query-builder/commit/34b913d1860cb1cf1f1f534153ea413342eed88d
