### ISSUE TITLE
Allow naming mutations

### ISSUE THREAD

**Issue by seantalbot-jisc** [atulmy/gql-query-builder#72]
The `gql.query` function takes an optional config object in which I can pass an `operationName` to name my query. This makes testing queries against a mock GQL server using MSW very easy as I can configure it to respond to incoming queries by the `operationName` https://mswjs.io/docs/getting-started/mocks/graphql-api#request-handler 

The `gql.mutation` function doesn't take this config object so I can't easily name mutations. This makes testing them with MSW much harder as I have to separately parse the GQL into an AST and locate the name of the underlying mutation that is called.

Could you add this config object to gql-query-builder?

**Comment by themagickoala** [comment]
@atulmy I've submitted a PR for this issue. We are hoping to use this package but the operationName for mutations is a hard requirement as we're using MSW too.

**Comment by atulmy** [comment]
@themagickoala thanks for your contribution, the package has been published:
https://www.npmjs.com/package/gql-query-builder/v/3.8.0
