### ISSUE TITLE
Are there any gql-query-builder playgrounds? or if there isn't a playground, if it is created then it would helpfull?

### ISSUE THREAD

**Issue by sevkioruc** [atulmy/gql-query-builder#77]
Developers who use gql-query-builder may want to see their queries/mutations values of output/variable.

**Comment by sevkioruc** [comment]
Developers who use gql-query-builder may want to see their queries/mutations values of output/variable.

**Comment by atulmy** [comment]
Are you looking for something like this: https://replit.com/@atulmy/gql-query-builder#index.js

**Comment by sevkioruc** [comment]
Yes, thank you @atulmy. Can i edit this file?

**Comment by atulmy** [comment]
You can fork it and edit 🙂

**Comment by sevkioruc** [comment]
Oh thank you so much :)
